### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by smunoz1988** [christianonoh/vecs-school-backend#18]
Hello reviewer! 

for this milestone, we create a Kanban board to manage the tasks of our "VECS SCHOOL" project. 

Group members (4): @vvoo21 / @christianonoh  / @smunoz1988 / @Ellyboi 

Link to project: https://github.com/users/christianonoh/projects/6

![image](https://github.com/christianonoh/vecs-school-backend/assets/64698693/c5a67b1e-0520-493a-a645-bbbac48b7b85)

**Comment by Meltrust** [comment]
Hi @smunoz1988 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @smunoz1988 ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  All cards have been assigned and pointed. 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️

- [ ] According to the project requirements:

![image](https://github.com/christianonoh/vecs-school-backend/assets/57421823/87c2fd0e-b26c-462f-8089-664c329fcee0)

At the time of this review, these are the pointings:

Ellyboi 49
christianonoh 49
vvoo21 61
smunoz1988 61

As you can see, there are huge points differences that are greater than the limit which is 5.  (61-49 = 12,  12 > 5)

Therefore:

- [ ] Kindly ensure nobody has a difference of 5 points as compared to any other person on the team.  The difference limit is 5.

That way, we will meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 💪 

_Tip:  Just reassign some tasks/play with the numbers until the requirement is met._




Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

**Comment by smunoz1988** [comment]
@Meltrust  thanks for the review. 

We reassign some tasks to match the requirement:

total hours from tasks: 

- Ellyboi 49
- christianonoh 49
- vvoo21 46
- smunoz1988 46

(+/- 3)

**Comment by Meltrust** [comment]
Hi @smunoz1988,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal, according to the requirement ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by smunoz1988** [comment]
@Meltrust  Thanks for the review!

Close Issue
